const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("brightside", {
  getState: () => ipcRenderer.invoke("state:get"),
  saveSettings: settings => ipcRenderer.invoke("settings:save", settings),
  completeOnboarding: name => ipcRenderer.invoke("onboarding:complete", name),
  getProductionPlan: () => ipcRenderer.invoke("production:get"),
  importProductionPlan: () => ipcRenderer.invoke("production:import"),
  createProductionItem: payload => ipcRenderer.invoke("production:create", payload),
  updateProductionItem: payload => ipcRenderer.invoke("production:update", payload),
  removeProductionItem: id => ipcRenderer.invoke("production:remove", id),
  openProductionFolder: () => ipcRenderer.invoke("production:open-folder"),
  getProductionBible: () => ipcRenderer.invoke("bible:get"),
  updateProductionBible: payload => ipcRenderer.invoke("bible:update", payload),
  openProductionBibleFolder: () => ipcRenderer.invoke("bible:open-folder"),
  createShot: payload => ipcRenderer.invoke("shot:create", payload),
  updateShot: payload => ipcRenderer.invoke("shot:update", payload),
  removeShot: id => ipcRenderer.invoke("shot:remove", id),
  rateTake: payload => ipcRenderer.invoke("take:rate", payload),
  setSceneAnchor: payload => ipcRenderer.invoke("scene:set-anchor", payload),
  openExternalEngine: id => ipcRenderer.invoke("engine:open", id),
  runAssistant: (text, engine) => ipcRenderer.invoke("assistant:run", text, engine),
  importProjectFiles: () => ipcRenderer.invoke("project:import"),
  removeProjectFile: id => ipcRenderer.invoke("project:remove", id),
  transcribe: (buffer, mime) => ipcRenderer.invoke("voice:transcribe", buffer, mime),
  createImage: request => ipcRenderer.invoke("image:create", request),
  navigate: url => ipcRenderer.invoke("higgs:navigate", url),
  checkForUpdates: () => ipcRenderer.invoke("update:check"),
  openProjectFolder: () => ipcRenderer.invoke("project:open-folder"),
  getAiKnowledge: () => ipcRenderer.invoke("knowledge:get"),
  importAiKnowledge: sourceType => ipcRenderer.invoke("knowledge:import", sourceType),
  saveAiKnowledgeText: payload => ipcRenderer.invoke("knowledge:save-text", payload),
  removeAiKnowledge: id => ipcRenderer.invoke("knowledge:remove", id),
  getContinuity: () => ipcRenderer.invoke("continuity:get"),
  createScene: payload => ipcRenderer.invoke("scene:create", payload),
  activateScene: id => ipcRenderer.invoke("scene:activate", id),
  importContinuity: category => ipcRenderer.invoke("continuity:import", category),
  addElementsToScene: ids => ipcRenderer.invoke("scene:add-elements", ids),
  moveWorkToFinal: filename => ipcRenderer.invoke("scene:move-final", filename),
  setScenePrivate: value => ipcRenderer.invoke("scene:set-private", value),
  setAssetPrivate: payload => ipcRenderer.invoke("asset:set-private", payload),
  chooseEditorDeliveryFolder: () => ipcRenderer.invoke("editor:choose-folder"),
  deliverFinalToEditor: filename => ipcRenderer.invoke("editor:deliver", filename),
  openEditorDeliveryFolder: () => ipcRenderer.invoke("editor:open-folder"),
  openSceneFolder: () => ipcRenderer.invoke("scene:open-folder"),
  decideApproval: decision => ipcRenderer.send("approval:decision", decision),
  onApproval: callback => ipcRenderer.on("approval:request", (_event, value) => callback(value)),
  onUrl: callback => ipcRenderer.on("higgs:url", (_event, value) => callback(value)),
  onApprovalBudget: callback => ipcRenderer.on("approval:budget", (_event, value) => callback(value)),
  onUpdateStatus: callback => ipcRenderer.on("update:status", (_event, value) => callback(value)),
  onContinuityChanged: callback => ipcRenderer.on("continuity:changed", (_event, value) => callback(value))
});
